name = "usd" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "usd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.usd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "Graph.facebook.com.usd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.usd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "englishtest-stage-7.duolingo.com.usd.fadztunnell.my.id"
custom_domain = true

[vars]
UUID = "9309b805-49fc-40f0-9591-1fb7b1948274"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
# UUID = "9309b805-49fc-40f0-9591-1fb7b1948274"
